language: node_js
dist: trusty
sudo: required
node_js: stable

# Build only master and release tags
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+(\.\d+)?$/

env:
  matrix:
  - PATH=$HOME/purescript:$PATH

install:
- export PURS_VERSION=v0.13.2
- wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$PURS_VERSION/linux64.tar.gz
- tar -xvf $HOME/purescript.tar.gz -C $HOME/
- chmod a+x $HOME/purescript
- npm install -g spago
- npm install
- spago install

script:
- spago build
- spago test
- spago docs
- npm run build
- node dist/main.js build-index

deploy:
  - provider: releases
    api_key: $API_KEY
    file:
      - dist/docs-search-app.js
      - dist/main.js
    skip_cleanup: true
    on:
      tags: true
    script:
      - echo 'done'
  - provider: npm
    api_key: $NPM_API_KEY
    email: klntsky@gmail.com
    skip_cleanup: true
    on:
      tags: true
      branch: master
