name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install
        run: |
          PURS_VERSION="$(curl -H "Authorization: token $GITHUB_API_TOKEN" --silent "https://api.github.com/repos/purescript/purescript/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')"
          echo "PureScript version: $PURS_VERSION"
          wget -O $HOME/purescript.tar.gz https://github.com/purescript/purescript/releases/download/$PURS_VERSION/linux64.tar.gz
          tar -xvf $HOME/purescript.tar.gz -C $HOME/
          chmod a+x $HOME/purescript
          npm install -g spago
          npm install
          spago install
      - name: Build
        run: |
          npm run build
          npm test
          spago docs --no-search
          ./dist/purescript-docs-search build-index
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/docs-search-app.js
            dist/purescript-docs-search
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
